import { describe, expect, test } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const readSource = (relativePath: string) =>
  readFileSync(resolve(process.cwd(), relativePath), 'utf8');

describe('Plan158 frontend legacy cleanup', () => {
  test('ProjectCockpit exposes a read-only v3 capability card summary', () => {
    const source = readSource('src/components/ProjectCockpitView.tsx');

    expect(source).toContain('当前作品能力卡');
    expect(source).toContain('作品资料概览 / 已配置');
    expect(source).toContain('当前作品已保存的资料数量');
    expect(source).toContain('本章使用');
    expect(source).toContain('进入正文编辑');
    expect(source).toContain('也可以先打开编辑器手写正文');
    expect(source).not.toContain('直接进入编辑器手写正文');
    expect(source).not.toContain('直接写正文');
    expect(source).not.toContain('直接写正文始终可用');
    expect(source).not.toContain('mountedSkillLoadout');
    expect(source).not.toContain('项目资料概览 / 已配置');
    expect(source).not.toContain('当前项目已保存');
    expect(source).not.toContain('临时叠加');
    expect(source).not.toContain('角色技能');
    expect(source).not.toContain('已装配技能');
  });

  test('QualityTab routes mount-skill recommendations to capability navigation', () => {
    const source = readSource('src/components/book-factory/QualityTab.tsx');

    expect(source).toContain("onSwitchTab?.('skills')");
    expect(source).toContain('进入作品能力中心');
    expect(source).not.toContain('进入能力中心');
    expect(source).not.toContain('[0, 1, 2]');
    expect(source).not.toContain('onAssignSkill(');
    expect(source).not.toContain('onRemoveSkill(');
    expect(source).not.toContain('mountedSkillLoadout.some');
  });

  test('AgentWorkspace uses author-facing capability copy', () => {
    const source = readSource('src/components/AgentWorkspace.tsx');

    expect(source).toContain('作品默认能力卡');
    expect(source).toContain('本章使用卡');
    expect(source).not.toContain('临时能力卡');
    expect(source).not.toContain('使用系统默认能力');
  });

  test('BookFactory avoids user-facing legacy deck copy', () => {
    const output = readSource('src/components/book-factory/BookFactoryOutput.tsx');
    const input = readSource('src/components/book-factory/BookFactoryInput.tsx');
    const view = readSource('src/components/book-factory/BookFactoryView.tsx');
    const details = readSource('src/components/book-factory/SkillCardDetails.tsx');
    const equip = readSource('src/components/book-factory/EquipPanel.tsx');
    const quality = readSource('src/components/book-factory/QualityTab.tsx');
    const outline = readSource('src/components/book-factory/OutlineTab.tsx');
    const workflow = readSource('src/components/book-factory/useBookFactory.ts');
    const packages = readSource('shared/lib/enhancement-packages.ts');

    expect(output).toContain('拆书卡结果');
    expect(output).toContain('保存到我的能力只是入库');
    expect(output).toContain('已保存到我的能力');
    expect(input).toContain('开始拆书并生成拆书卡');
    expect(view).toContain('专属拆书卡');
    expect(view).toContain('生成可保存的专属拆书卡候选');
    expect(view).not.toContain('AI 自动提炼文风');
    expect(view).not.toContain('factoryIntent');
    expect(view).not.toContain('ACTIVE SOP STEP');
    expect(output).toContain('保存卡组草稿');
    expect(output).toContain('仅保存当前拆书卡到我的能力');
    expect(details).toContain('为什么这张拆书卡成立');
    expect(equip).toContain('作品卡组待选');
    expect(equip).toContain('提交到作品卡组待选');
    expect(outline).toContain('确认采用此大纲');
    expect(outline).toContain('确认采用此候选会覆盖当前大纲');
    expect(outline).toContain('基于当前主纲或选中的导入大纲生成候选');
    expect(outline).not.toContain('直接采用此大纲');
    expect(outline).not.toContain('将读取当前主纲');
    expect(packages).toContain('把跨章节奏与悬念卡提交到作品卡组待选');
    expect(packages).toContain('从多个候选流程中显式选择一条作品创作流程');
    expect(packages).toContain('同一作品只能选择一条创作流程');
    expect(packages).toContain('辅助提炼主笔文风、节奏与钩子候选卡');
    expect(packages).toContain('整理为待确认写作规则');
    expect(packages).toContain('保存后由作者选择卡组位置并确认融合');
    expect(output).toContain('结果就绪后会展示最新候选，保存后才进入我的能力');
    expect(equip).toContain('请选择目标作品');
    expect(quality).toContain('本章使用');
    expect(quality).toContain('获得可确认的局部精修预览');
    expect(quality).toContain('手术精修预览片段');
    expect(quality).toContain('本轮预览');
    expect(quality).toContain('可在下方生成精修预览');
    expect(quality).toContain('生成精修预览');
    expect(quality).toContain('执行局部手术精修');
    expect(quality).not.toContain('获得可一键局部精修的手术方案');
    expect(quality).not.toContain('一键手术精修');
    expect(quality).not.toContain('本轮一键手术');
    expect(quality).not.toContain('推荐使用下方一键精修');
    expect(quality).not.toContain('一键执行局部手术精修');
    expect(workflow).toContain('作品卡组最多');
    expect(`${output}\n${input}\n${view}\n${details}\n${equip}\n${quality}\n${outline}\n${workflow}\n${packages}`).not.toMatch(/萃取结果 \(Skill Deck\)|Deck 已保存|保存整组 Deck|开始拆书与萃取 Skill|为什么这张 Skill 成立|另存 Deck|项目 Deck|作品 Flow|启用一条 Flow|一键提炼成主笔文风|系统直接智能融合|强力融合成写作指令|自动替换当前卡片|正在后台深度分析文本风格|开始拆书与萃取技能卡|专属拆书技能卡|为什么这张技能卡成立|当前拆书卡已保存|保存只是入库|保存整组卡组|技能库|作品技能卡组|项目技能卡组|项目卡组|项目候选卡组|提交到卡组待选|装配到作品|需装配后计算|建议装配位|已叠加|撤销叠加|叠加拆书卡|当前配置候选|加入目标作品卡组|加入作品卡组候选|加入卡组候选|保存并加入目标作品卡组|应用到目标作品才影响写作|只保存能力卡，不加入作品|直接采用此大纲/);
  });

  test('pre-writing entry points use capability-card copy', () => {
    const appShell = readSource('src/components/AppShell.tsx');
    const library = readSource('src/components/Library.tsx');
    const receipt = readSource('src/components/book-factory/ContextReceipt.tsx');
    const onboarding = readSource('src/components/WorldBibleOnboarding.tsx');
    const productionPanel = readSource('src/components/AgentWorkspaceProductionPanel.tsx');
    const workspace = readSource('src/components/AgentWorkspace.tsx');
    const intelligenceContext = readSource('src/lib/hooks/useEditorIntelligenceContext.ts');

    expect(appShell).toContain('配置能力卡');
    expect(appShell).toContain('进入作品后可打开编辑器写作、整理设定和配置能力卡。');
    expect(appShell).toContain('编辑器会展示章节、分镜、世界观与能力卡配置');
    expect(library).toContain('getProjectCapabilityCardCount(novel)');
    expect(productionPanel).toContain('getProjectCapabilityCardCount(novel, mountedSkillLoadout)');
    expect(workspace).toContain('getProjectCapabilityCardIds(novel, mountedSkillLoadout)');
    expect(workspace).toContain('有助于关系网图谱在写作时识别并高亮');
    expect(workspace).not.toContain('能自动提取高亮');
    expect(intelligenceContext).toContain('getProjectCapabilityCardIds(novel, mountedSkillLoadout)');
    expect(receipt).toContain('能力卡:');
    expect(onboarding).toContain('推荐的角色写作配置');
    expect(onboarding).toContain('可稍后在作品能力中心调整');
    const createOnboardingDraftStart = appShell.indexOf('ideaSeed: onboardingDraft?.ideaSeed');
    const createOnboardingDraftBlock = appShell.slice(
      createOnboardingDraftStart,
      appShell.indexOf('setActiveSetupTaskKey', createOnboardingDraftStart),
    );
    expect(createOnboardingDraftBlock).toContain('acceptedSkillIds: []');
    const acceptRecommendedSkillsBlock = appShell.slice(
      appShell.indexOf('const handleAcceptRecommendedSkills'),
      appShell.indexOf('if (loading)'),
    );
    expect(acceptRecommendedSkillsBlock).toContain('acceptedRecommendedSkills: true');
    expect(acceptRecommendedSkillsBlock).not.toContain('updateNovel(');
    expect(acceptRecommendedSkillsBlock).not.toContain('mountedSkillIds');
    expect(acceptRecommendedSkillsBlock).not.toContain('mountedSkillLoadout');
    expect(appShell).not.toContain('进入作品后可直接写作、设定和挂载技能。');
    expect(appShell).not.toContain('进入作品后可直接写作、设定和配置能力卡。');
    expect(appShell).not.toContain('编辑器会汇总章节、分镜、世界观与能力卡配置');
    expect(library).not.toContain('getProjectDeckIds(getProjectCapabilityProfile(novel))');
    expect(library).not.toContain('能力卡 ${novel.mountedSkillIds?.length || 0}/3');
    expect(library).not.toContain('技能 ${novel.mountedSkillIds?.length || 0}/3');
    expect(receipt).not.toContain('装配技能:');
    expect(onboarding).toContain('不会自动应用');
    expect(onboarding).not.toContain('可稍后在能力商店调整');
    expect(onboarding).not.toMatch(/推荐 Role Skill|接受推荐 Role Skill|Overlay（可选）|暂无阶段 Overlay|不会自动装配/);
  });

  test('capability center and writing style use author-facing card copy', () => {
    const studio = readSource('src/components/SkillsStudioView.tsx');
    const stageCards = readSource('src/lib/capability-stage-cards.ts');
    const preference = readSource('src/components/skills/ProjectPreferencePanel.tsx');
    const loadout = readSource('src/components/skills/SkillLoadoutBoard.tsx');
    const drawer = readSource('src/components/skills/SkillDetailDrawer.tsx');
    const mapPanel = readSource('src/components/skills/SkillMapPanel.tsx');
    const testBench = readSource('src/components/skills/SkillTestBench.tsx');
    const skillCard = readSource('src/components/skills/SkillCard.tsx');
    const welcome = readSource('src/components/WelcomeView.tsx');
    const appShell = readSource('src/components/AppShell.tsx');
    const governance = readSource('src/lib/capability-governance.ts');
    const worldBible = readSource('src/components/WorldBibleView.tsx');
    const bookFactoryOutput = readSource('src/components/book-factory/BookFactoryOutput.tsx');
    const bookFactoryUse = readSource('src/components/book-factory/useBookFactory.ts');
    const continuationPackView = readSource('src/components/ContinuationPackView.tsx');
    const continuationImportView = readSource('src/components/ContinuationImportView.tsx');
    const writingSurface = readSource('src/components/WritingSurface.tsx');
    const productionRunReview = readSource('src/components/ProductionRunReview.tsx');
    const settingsModal = readSource('src/components/SettingsModal.tsx');
    const aiAssistant = readSource('src/components/AIAssistant.tsx');
    const tracePanel = readSource('src/components/AgentWorkspaceTracePanel.tsx');
    const continuationOverview = readSource('src/components/ContinuationOverviewPanel.tsx');
    const premiumUpgrade = readSource('src/components/commercial/PremiumUpgradeModal.tsx');
    const knowledgePanel = readSource('src/components/AgentWorkspaceKnowledgePanel.tsx');

    expect(studio).toContain('作品卡组');
    expect(studio).toContain('拆书卡');
    expect(studio).toContain('管理作品默认能力与本章写法');
    expect(studio).toContain('本章使用规则只影响当前章');
    expect(studio).toContain('本章使用规则只影响当前章；系统护栏参与生成与审稿检查。');
    expect(studio).not.toContain('本章技法只影响当前章');
    expect(appShell).toContain('本章使用规则只影响当前章');
    expect(appShell).not.toContain('本章技法只影响当前章');
    expect(studio).toContain('你还没有保存能力卡');
    expect(studio).toContain('辅助写作推荐能力卡');
    expect(studio).toContain('能力卡如何影响写作');
    expect(studio).toContain('加入本次配置候选');
    expect(studio).toContain('重新预览本次配置');
    expect(studio).toContain('本次配置仍待应用；应用成功后才更新作品状态。');
    expect(studio).toContain('点击应用配置后才写入作品');
    expect(studio).toContain('请再次点击应用配置以写入作品');
    expect(knowledgePanel).toContain('本章使用规则只影响当前章节');
    expect(knowledgePanel).not.toContain('本章技法已作为本章使用规则显示');
    expect(knowledgePanel).toContain('本章使用规则');
    expect(knowledgePanel).not.toContain('本章技法会显示在下方本章使用卡区域');
    expect(stageCards).toContain('配置到作品：应用配置后写入大纲技法');
    expect(stageCards).toContain('配置到作品：应用配置后写入设定素材');
    expect(stageCards).toContain('配置到作品：应用配置后写入作品默认配置');
    expect(studio).toContain('配置到作品：应用配置后写入创作流程');
    expect(stageCards).toContain('应用配置后设为作品默认');
    expect(stageCards).toContain('应用配置后写入本章规则');
    expect(stageCards).toContain('应用配置后可写入本章规则');
    expect(studio).toContain('先勾选待提交，再加入本次配置候选并按每步结果确认下一步');
    expect(studio).toContain('先勾开篇结构，再按需选择正文表达技法');
    expect(studio).not.toContain('先加入本次配置候选，再按每步结果确认下一步');
    expect(studio).not.toContain('先勾开篇结构，再按需启用正文表达技法');
    expect(studio).not.toContain('点击应用后才保存到作品');
    expect(studio).not.toContain('点击应用配置后才保存到作品');
    expect(studio).not.toContain('请再次点击应用以保存配置');
    expect(stageCards).not.toContain('配置到作品：应用后保存大纲技法');
    expect(stageCards).not.toContain('配置到作品：应用后保存设定素材');
    expect(stageCards).not.toContain('应用后设为作品默认');
    expect(stageCards).not.toContain('应用后写入本章规则');
    expect(stageCards).not.toContain('应用配置后可保存为本章规则');
    expect(stageCards).not.toContain('写入作品长期默认');
    expect(studio).not.toContain('写入作品长期默认');
    expect(studio).not.toContain('重新预览当前配置');
    expect(studio).not.toContain('当前配置仍待应用');
    expect(studio).not.toContain('当前配置已变化');
    expect(studio).toContain('下一步：审稿诊断待运行');
    expect(studio).toContain('下一步：辅助动作待运行');
    expect(studio).toContain('下一步：应用配置后写入作品');
    expect(studio).toContain('下一步：应用配置后写入本章规则');
    expect(studio).toContain('下一步：应用配置后写入作品卡组');
    expect(studio).toContain('下一步：应用配置后写入写前提醒');
    expect(studio).toContain('下一步：应用配置后写入创作流程');
    expect(studio).toContain('下一步：选择卡组位置后应用');
    expect(studio).not.toContain('下一步：应用配置后保存作品卡组');
    expect(studio).not.toContain('下一步：应用配置后保存为本章规则');
    expect(studio).not.toContain('下一步：应用配置后保存到作品');
    expect(studio).not.toContain('下一步：应用配置后保存写前提醒');
    expect(studio).not.toContain('下一步：应用配置后保存创作流程');
    expect(studio).not.toContain('下一步：应用配置后生效');
    expect(studio).not.toContain('下一步：加入作品卡组后生效');
    expect(studio).toContain('流程、技法、拆书卡和辅助动作');
    expect(studio).not.toContain('下一步：工具待运行');
    expect(studio).not.toContain('流程、技法、拆书卡和工具');
    expect(studio).toContain('结果：不可用，已跳过');
    expect(studio).not.toContain('不自动应用');
    expect(studio).toContain('能力配置尚未应用');
    expect(studio).toContain('未应用的能力配置');
    expect(writingSurface).toContain('生成一章预览');
    expect(writingSurface).toContain('在下面主编辑器手写正文');
    expect(productionRunReview).toContain('生成一章预览');
    expect(productionRunReview).toContain('结果只会进入预览，点击接受后才写入章节和状态账本');
    expect(writingSurface).not.toContain('自动生产一章');
    expect(writingSurface).not.toContain('正文直接写进');
    expect(productionRunReview).not.toContain('单章自动生产');
    expect(studio).not.toContain('能力库');
    expect(bookFactoryOutput).not.toContain('能力库');
    expect(bookFactoryUse).not.toContain('能力库');
    expect(premiumUpgrade).toContain('能力卡集');
    expect(premiumUpgrade).not.toContain('能力库');
    expect(preference).toContain('使用能力卡');
    expect(preference).toContain('作品写法画像');
    expect(preference).not.toContain('项目写法画像');
    expect(preference).not.toContain('这个项目的写法偏好');
    expect(knowledgePanel).toContain('作品主卡');
    expect(knowledgePanel).not.toContain('项目主卡');
    expect(knowledgePanel).toContain('未配置系统检查规则');
    expect(knowledgePanel).not.toContain('未启用系统检查规则');
    expect(governance).toContain("project: '作品默认'");
    expect(governance).toContain("chapter: '本章使用'");
    expect(governance).not.toContain("project: '项目'");
    expect(governance).not.toContain("chapter: '章节'");
    expect(preference).toContain('能力权重');
    expect(loadout).toContain('旧配置待整理');
    expect(welcome).toContain('能力卡配置');
    expect(welcome).toContain('生成拆书卡');
    expect(welcome).toContain('深度导入已有资产大纲');
    expect(welcome).toContain('自适应推荐分析');
    expect(welcome).toContain('选择推荐创作流程');
    expect(welcome).toContain('选择此立项');
    expect(welcome).toContain('从模糊灵感整理立项候选');
    expect(welcome).toContain('生成立项候选');
    expect(welcome).toContain('整理衔接建议');
    expect(welcome).toContain('保存文风滤镜与创作规则，配置后参与后续生成。');
    expect(welcome).toContain('提供可选创作流程');
    expect(welcome).toContain('生成错别字与大路货词汇精修预览');
    expect(welcome).toContain('生成核心主角候选，确认后写入第一章主角人设卡。');
    expect(welcome).toContain('保存作品和第一章后打开编辑器，进入空白正文编辑区。');
    expect(worldBible).toContain('生成大纲与设定拆解草稿，确认后再导入');
    expect(welcome).not.toContain('启用推荐创作流程');
    expect(welcome).not.toContain('自适应启用分析');
    expect(welcome).not.toContain('一键开始此立项');
    expect(welcome).not.toContain('一键重构立项方向');
    expect(welcome).not.toContain('一键智能立项');
    expect(welcome).not.toContain('一键理顺衔接');
    expect(welcome).not.toContain('保存作品和第一章后直接进入编辑器');
    expect(welcome).not.toContain('不自动生产');
    expect(welcome).not.toContain('直接融入生成流');
    expect(welcome).not.toContain('一键对齐爆款红线');
    expect(welcome).not.toContain('一键定向精修重写');
    expect(welcome).not.toContain('自动生成核心主角，写入第一章主角人设卡。');
    expect(worldBible).not.toContain('一键完成大纲与设定的多层析拆解');
    expect(welcome).toContain('纳入高连贯性检查候选');
    expect(welcome).not.toContain('自动纳入高连贯性升级检查');
    expect(appShell).toContain('能力卡配置');
    expect(bookFactoryUse).toContain('提交到作品卡组待选');
    expect(bookFactoryUse).toContain('已提交到作品卡组待选，请前往作品能力中心选择主卡或辅卡并应用配置。');
    expect(bookFactoryUse).not.toContain('后续写作会读取');
    expect(bookFactoryUse).not.toContain('被写作读取');
    expect(appShell).not.toContain('助手会读取当前作品与章节上下文');
    expect(settingsModal).toContain('后续 AI 请求会使用这套模板');
    expect(settingsModal).toContain('用于后续 AI 请求组装');
    expect(settingsModal).toContain('试跑会用当前编辑草稿发起一次测试');
    expect(settingsModal).not.toContain('试跑会直接使用当前编辑内容');
    expect(settingsModal).not.toContain('后续 AI 请求会直接读取这套模板');
    expect(settingsModal).not.toContain('被后续 AI 请求读取');
    expect(aiAssistant).toContain('基于已打开的作品与章节资料辅助你整理候选');
    expect(aiAssistant).toContain('给我一段可编辑的正文候选');
    expect(aiAssistant).toContain('确认提取结果后再写入该作品的「设定集」');
    expect(aiAssistant).not.toContain('读取当前章节上下文');
    expect(aiAssistant).not.toContain('可以直接接上的正文候选');
    expect(aiAssistant).not.toContain('AI将自动提取');
    expect(aiAssistant).not.toContain('并写入该作品的「设定集」库中');
    expect(settingsModal).toContain('前置规则');
    expect(settingsModal).not.toContain('前置注入');
    expect(tracePanel).toContain('识别出场人物、地点与道具候选');
    expect(tracePanel).toContain('纳入本章生成参考');
    expect(tracePanel).not.toMatch(/自动抓取|自动注入|Pruning/);
    expect(continuationOverview).toContain('作为后续续写参考');
    expect(continuationOverview).toContain('生成预览时会预选该资料包');
    expect(continuationOverview).toContain('确认资料包后开始续写');
    expect(continuationOverview).toContain('已确认资料包打开生产面板');
    expect(continuationOverview).toContain('带着当前资料包进入续写');
    expect(continuationOverview).not.toMatch(/稳定吃到上下文|直接挂上|本次自动生产将默认使用/);
    expect(continuationOverview).not.toContain('直接进入资料包续写');
    expect(continuationOverview).not.toContain('直接进入生产面板');
    expect(continuationOverview).not.toContain('直接进入续写');
    expect(continuationPackView).toContain('确认资料包');
    expect(continuationPackView).toContain('回来审核或确认');
    expect(continuationPackView).toContain('生成预览摘要');
    expect(continuationPackView).not.toContain('确认启用');
    expect(continuationPackView).not.toContain('审核或启用');
    expect(continuationPackView).not.toContain('自动生产摘要');
    expect(continuationImportView).toContain('确认后再进入写作');
    expect(continuationImportView).toContain('确认资料包后继续写');
    expect(continuationImportView).toContain('可确认后进入续写');
    expect(continuationImportView).toContain('生成剧情位置、角色状态和关键硬设定候选摘要');
    expect(continuationImportView).toContain('支持解包 .zip 和多级目录');
    expect(continuationImportView).toContain('解析后会生成候选作品名');
    expect(continuationImportView).not.toContain('自动整理剧情位置');
    expect(continuationImportView).not.toContain('支持自动提取 .zip');
    expect(continuationImportView).not.toContain('解析后会自动生成默认作品名');
    expect(continuationImportView).not.toContain('再带你直接进入写作');
    expect(continuationImportView).not.toContain('直接继续写');
    expect(continuationImportView).not.toContain('直接把你送进编辑器');
    expect(continuationImportView).not.toContain('可直接进入续写');
    expect(writingSurface).toContain('新建第一章');
    expect(writingSurface).not.toContain('一键开始您的第一章');
    expect(drawer).toContain('选择一张能力卡');
    expect(drawer).toContain('能力卡有哪些能力');
    expect(drawer).toContain('能力卡名称');
    expect(drawer).toContain('主能力');
    expect(drawer).toContain('能力画像');
    expect(drawer).toContain('保存当前能力卡');
    expect(drawer).toContain('保存融合为新版本');
    expect(drawer).not.toContain('保存当前版本');
    expect(drawer).not.toContain('保存融合候选');
    expect(drawer).toContain('关闭能力卡详情');
    expect(mapPanel).toContain('能力卡地图');
    expect(testBench).toContain('能力卡试跑');
    expect(testBench).not.toContain('能力卡试驾');
    expect(welcome).toContain('爽点大纲规则');
    expect(welcome).not.toContain('爽点大纲规约');
    expect(skillCard).toContain('打开能力卡');
    expect(skillCard).toContain('加入本次配置候选');
    expect(skillCard).not.toContain('当前配置候选');
    expect(studio).not.toContain('再加入候选');
    expect(`${studio}\n${preference}\n${loadout}\n${drawer}\n${mapPanel}\n${testBench}\n${skillCard}\n${welcome}\n${appShell}\n${governance}`).not.toMatch(/技能库|技能卡组|项目技能卡组|待分配技能卡|拆书技能卡|装配 Skill|装配能力|旧装配待整理|确认删除这个技能|技能库中删除|已装配|加入技能卡组|未命名 Skill|拆书技能|拆书生成技能|辅助写作推荐技能卡|技能如何影响写作|提交所选组件|当前组件暂不可运行|选择一张技能卡|技能卡牌有哪些能力|对应技能|技能融合|本章临时使用|临时配置|关闭技能详情|技能名称|技能描述|使用当前技能|深度挂载已有资产大纲|自适应挂载分析|挂载至第一章主角人设卡|自动挂载高连贯性升级限制|挂载 \$\{bubbleData|Skill 地图|技能总数|有使用反馈的 Skill|技能试驾|当前技能版本|当前职责卡|组合职责卡|对比职责卡|职责权重|主职责|职责画像|打开技能|删除技能|进行装备/);
  });

  test('runtime card messages avoid stack and skill-card wording', () => {
    const recommendations = readSource('src/lib/hooks/useEditorRecommendationCards.ts');
    const packages = readSource('shared/lib/enhancement-packages.ts');
    const extraction = readSource('server/helpers/skill-extraction.ts');

    expect(recommendations).toContain('已加入本章使用卡');
    expect(recommendations).toContain('已移出本章使用卡');
    expect(packages).toContain('拆书卡候选');
    expect(extraction).toContain('保底拆书卡');
    expect(`${recommendations}\n${packages}\n${extraction}`).not.toMatch(/叠加拆书卡|已成功叠加|撤销叠加|拆书技能卡候选|保底技能卡/);
  });

  test('runtime prompts and errors avoid legacy mount wording', () => {
    const skillRoutes = readSource('server/routes/skills.ts');
    const validation = readSource('server/validation.ts');
    const copilotStage = readSource('src/lib/copilot-stage.ts');
    const promptAssets = readSource('shared/lib/prompt-assets.ts');
    const promptTemplates = readSource('shared/config/prompt-templates.ts');
    const promptCatalog = readSource('shared/lib/prompt-governance-catalog.ts');
    const publicCatalog = readSource('shared/lib/public-skill-catalog.ts');
    const promptHelpers = readSource('server/helpers/prompt-helpers.ts');
    const writingStyleService = readSource('server/helpers/writing-style-service.ts');
    const capabilityManifest = readSource('server/capabilities/manifest.ts');
    const skillFusion = readSource('src/lib/skill-fusion.ts');
    const dbSkills = readSource('server/lib/db/skills.ts');
    const qualityGates = readSource('shared/lib/quality-gates.ts');
    const bookSkillAggregation = readSource('shared/lib/book-skill-aggregation.ts');
    const auditRoute = readSource('server/routes/audit.ts');
    const rewritePrompt = readSource('shared/lib/rewrite-prompt.ts');
    const promptRecommender = readSource('shared/lib/prompt-recommender.ts');
    const fusionTests = readSource('tests/skill-fusion.test.ts');
    const dbSkillVersioningTests = readSource('tests/db-skill-versioning.test.ts');
    const editorView = readSource('src/components/EditorView.tsx');
    const capabilityCardCount = readSource('src/lib/capability-card-count.ts');
    const productionRoute = readSource('server/routes/production.ts');
    const utilityRoute = readSource('server/routes/utilities.ts');
    const outlinesRoute = readSource('server/routes/outlines.ts');
    const canonPatchesRoute = readSource('server/routes/canon-patches.ts');
    const exportRoute = readSource('server/routes/export.ts');
    const dbRoute = readSource('server/routes/db.ts');
    const simpleLlmRoute = readSource('server/routes/simple-llm.ts');
    const promptTestRoute = readSource('server/routes/prompt-test.ts');
    const worldRoute = readSource('server/routes/world.ts');
    const outlineSource = readSource('server/capabilities/outline-source.ts');
    const agentsRoute = readSource('server/routes/agents.ts');
    const continuationRoute = readSource('server/routes/continuation.ts');
    const onboardingRoute = readSource('server/routes/onboarding.ts');
    const storyCardsHelper = readSource('server/helpers/story-cards.ts');
    const preferenceFlywheel = readSource('shared/lib/preference-flywheel.ts');
    const continuationPackParse = readSource('shared/lib/continuation-pack-parse.ts');

    expect(skillRoutes).toContain('暂时未能解析为能力卡');
    expect(validation).toContain('最多只能使用 3 张能力卡');
    expect(copilotStage).toContain('查看能力配置');
    expect(promptAssets).toContain('拆出的能力卡要能直接指导写作');
    expect(promptTemplates).toContain('萃取可组合的拆书卡组');
    expect(promptTemplates).toContain('而非能力卡 JSON');
    expect(promptTemplates).toContain('能力卡规则');
    expect(promptTemplates).toContain('预期能力卡规则');
    expect(promptTemplates).toContain('当前启用的能力卡规则');
    expect(promptTemplates).not.toMatch(/写作卡牌规约|叙事 DNA 规约|Narrative DNA/);
    expect(promptTemplates).not.toMatch(/Skill约束|Skills DNA|Skill 插件|Skill Card|Skill 中|Skill规定/);
    expect(promptCatalog).toContain('生成后需保存并配置到作品卡组');
    expect(promptCatalog).not.toContain('自动应用至写作中');
    expect(promptCatalog).toContain('可用于写作的节奏拆书卡');
    expect(publicCatalog).toContain('生成后需保存并配置到作品卡组');
    expect(publicCatalog).not.toContain('自动应用至写作中');
    expect(publicCatalog).toContain('可用于写作的节奏拆书卡');
    expect(publicCatalog).toContain('章节梗概生成');
    expect(publicCatalog).toContain('长篇爆款拆解与脑洞生成');
    expect(publicCatalog).toContain('爆款拆解与脑洞生成');
    expect(publicCatalog).toContain('降 AI 润色 1.0');
    expect(publicCatalog).toContain('降 AI 润色 2.0');
    expect(publicCatalog).toContain('融梗换心候选生成');
    expect(publicCatalog).not.toContain('一键生成章节梗概');
    expect(publicCatalog).not.toContain('长篇一键破解爆款小说并生成脑洞');
    expect(publicCatalog).not.toContain('一键破解爆款并生成脑洞');
    expect(publicCatalog).not.toContain('一键润色降ai');
    expect(publicCatalog).not.toContain('一键融梗换心');
    expect(preferenceFlywheel).toContain('当前作品写法偏好');
    expect(preferenceFlywheel).not.toContain('当前项目偏好');
    expect(continuationPackParse).toContain('你是小说作品接管编辑');
    expect(continuationPackParse).not.toContain('你是小说项目接管编辑');
    expect(promptHelpers).toContain('当前启用的写作能力卡组');
    expect(promptHelpers).toContain('当前启用的拆书卡规则');
    expect(promptHelpers).not.toMatch(/Flavor Overlays|Deconstruction Card Injector|White-Label Transfer|Composite Narrative Signature/);
    expect(writingStyleService).toContain('本章使用卡当前不可运行');
    expect(writingStyleService).toContain('作品卡组能力卡不能重复');
    expect(writingStyleService).toContain('本章写法卡规则');
    expect(writingStyleService).toContain('主笔能力卡');
    expect(capabilityManifest).toContain('能力卡不允许用于当前作用域');
    expect(skillFusion).toContain('已授权的能力卡融合');
    expect(dbSkills).toContain('两个不同且存在的能力卡');
    expect(qualityGates).toContain('张能力卡为模板化输出');
    expect(bookSkillAggregation).toContain('规则约束时配置到本次写作');
    expect(auditRoute).toContain('自适应启用了以下高级审读维度');
    expect(auditRoute).not.toMatch(/Audit job not found|Audit job is not cancellable|Audit job cancelled|Audit job expired|Audit job database generation mismatch|Rate limited|novelId is required|chapterId and databaseGeneration are required|Database changed|Database changed during rewrite|error: 'Cancelled'/);
    expect(rewritePrompt).toContain('当前启用的能力卡');
    expect(rewritePrompt).toContain('当前启用的能力卡规则');
    expect(promptHelpers).toContain('检测到已启用');
    expect(promptRecommender).toContain('推荐选择长篇商业连载流程');
    expect(promptRecommender).not.toContain('推荐启用长篇商业连载流程');
    expect(promptRecommender).toContain('capabilityProfile?.activeFlowId');
    expect(promptRecommender).toContain('capabilityProfile?.projectSkillDeck?.mainCardId');
    expect(copilotStage).toContain('调整能力配置');
    expect(copilotStage).toContain('作品默认能力卡');
    expect(copilotStage).toContain('本章分镜');
    expect(copilotStage).toContain('审稿意见');
    expect(editorView).toContain('这张本章使用卡已失效或未获得授权');
    expect(editorView).toContain('正在运行能力卡');
    expect(editorView).toContain('审稿卡诊断报告');
    expect(editorView).toContain('精修卡修改预览');
    expect(editorView).toContain('应用精修预览');
    expect(editorView).toContain('返回作品能力中心');
    expect(editorView).not.toContain('返回能力中心');
    expect(editorView).toContain('本次能力来源');
    expect(editorView).toContain('getProjectCapabilityCardCount(liveNovel, mountedSkillLoadout)');
    expect(capabilityCardCount).toContain('getProjectDeckIds(getProjectCapabilityProfile(novel))');
    expect(productionRoute).toContain('规划阶段能力卡与护栏');
    expect(productionRoute).toContain('正文阶段能力卡与护栏');
    expect(productionRoute).toContain('审稿阶段能力卡与护栏');
    expect(productionRoute).toContain('正文生成请求过于频繁，请稍后再试。');
    expect(productionRoute).toContain('请先选择要生成正文的作品。');
    expect(productionRoute).toContain('生成任务来自旧版本数据库，请刷新后重试。');
    expect(productionRoute).toContain('这版正文尚未完成审稿确认，请先确认风险后再应用。');
    expect(productionRoute).not.toMatch(/planner stage prompt|writer stage prompt|critic stage prompt|character state|learned preferences|Rate limited|novelId is required|Novel not found|Internal server error|Production run database generation mismatch|Production version database generation mismatch|Audit confirmation required/);
    expect(utilityRoute).toContain('审稿卡：');
    expect(utilityRoute).toContain('精修卡：');
    expect(utilityRoute).toContain('当前章节正文');
    expect(utilityRoute).toContain('选中正文片段');
    expect(utilityRoute).toContain('数据库已变化，请刷新后重新运行能力工具。');
    expect(utilityRoute).toContain('选中文本已变化，请重新选择后再运行能力工具。');
    expect(utilityRoute).not.toMatch(/chapterId and databaseGeneration are required|invalid capability request|database generation changed|novel not found|chapter not found|chapter does not belong to novel|selection is outside chapter content|utility request failed/);
    expect(outlinesRoute).toContain('数据库已变化，请刷新大纲后重试。');
    expect(canonPatchesRoute).toContain('数据库已变化，请刷新大纲变更后重试。');
    expect(`${outlinesRoute}\n${canonPatchesRoute}`).not.toMatch(/invalid outline request|outline request failed|OUTLINE_GENERATION_STALE: database generation changed|novel not found|outline not found|invalid canon patch request|canon patch request failed|CANON_PATCH_GENERATION_STALE: database generation changed|patch not found|CANON_PATCH_STALE: canon patch base is stale/);
    expect(exportRoute).toContain('作品导出失败，请稍后重试。');
    expect(dbRoute).toContain('数据库操作失败，请稍后重试。');
    expect(`${exportRoute}\n${dbRoute}`).not.toMatch(/Novel not found|Internal server error/);
    expect(simpleLlmRoute).toContain('片段扩写请求过于频繁，请稍后再试。');
    expect(simpleLlmRoute).toContain('请先输入要扩写的片段。');
    expect(simpleLlmRoute).not.toMatch(/Rate limited|Database changed during fragment expansion|Content is required|Fragment input exceeds the cost limit|Client disconnected before fragment completion|Internal server error/);
    expect(promptTestRoute).toContain('提示词试跑请求过于频繁，请稍后再试。');
    expect(promptTestRoute).not.toMatch(/Rate limited|Invalid prompt template test request|Unknown template key|Template rendered to empty prompt|Internal server error/);

    expect(worldRoute).toContain('规划阶段能力卡与流程');
    expect(worldRoute).not.toMatch(/Job not found|Job is not cancellable|World job cancelled|World job expired|World job database generation is invalid|Database replaced during world job|novelId is required|Rate limited|databaseGeneration is required|Chapter content is required|Chapters array is required|Character state update queued in background|Database changed during bio generation|Internal server error|error: 'Cancelled'/);
    expect(`${worldRoute}\n${outlineSource}`).not.toMatch(/Planner 技法|Only approved packs can be used for outline generation|source belongs to another novel|continuation pack is not approved|document selection is invalid|document is not in the pack|primary document appears to be a report|primary document is not an outline candidate|document role cannot become an outline source|source exceeds the configured budget/);
    expect(agentsRoute).not.toMatch(/Job not found|Job is not cancellable|Editor-agent job cancelled|Editor-agent job expired|Editor-agent job database generation mismatch|Invalid editor-agent request|Continuation pack not found|Continuation pack does not belong to editor-agent novel|novelId is required outside onboarding|Rate limited|Database changed during inspiration|Database changed before draft completion|error: 'Database changed'|error: 'Cancelled'/);
    expect(continuationRoute).toContain('资料设定提取请求过于频繁，请稍后再试。');
    expect(continuationRoute).toContain('同步到世界观请求过于频繁，请稍后再试。');
    expect(continuationRoute).not.toMatch(/Rate limited|Parse-doc job cancelled|error: 'Cancelled'|novelId is required|At least one document is required|packId is required/);
    expect(`${onboardingRoute}\n${storyCardsHelper}\n${readSource('server/helpers/onboarding-llm-session.ts')}`).not.toMatch(/Story card job not found|Story-card job expired|Job not found|Job is not cancellable|Story-card job cancelled|World-setup job cancelled|World-setup job expired|World-setup job database generation mismatch|Onboarding model session|Invalid onboarding model operation|ideaSeed is required|taskTitle is required|documentText is required|Internal server error|Rate limited|error: 'Cancelled'/);
    expect(`${skillRoutes}\n${readSource('server/helpers/skill-extraction.ts')}`).not.toMatch(/Skill extraction job|Skill extraction aborted|Job is not cancellable|Rate limited/);
    expect(`${skillRoutes}\n${validation}\n${copilotStage}\n${promptAssets}\n${promptTemplates}\n${promptCatalog}\n${publicCatalog}\n${promptHelpers}\n${writingStyleService}\n${capabilityManifest}\n${skillFusion}\n${dbSkills}\n${qualityGates}\n${bookSkillAggregation}\n${auditRoute}\n${rewritePrompt}\n${promptRecommender}\n${editorView}\n${simpleLlmRoute}\n${promptTestRoute}\n${worldRoute}\n${outlineSource}\n${outlinesRoute}\n${canonPatchesRoute}\n${agentsRoute}\n${continuationRoute}\n${onboardingRoute}`).not.toMatch(/暂时未能解析为技能卡|最多只能挂载 3 个技能卡|查看技能挂载|可直接挂载|当前挂载的写作卡牌规约|写作卡牌规约|叙事 DNA 规约|Narrative DNA|当前挂载的复合叙事 DNA|当前挂载的叙事 DNA|叙事 DNA 插件|检测到挂载了|推荐挂载长篇商业连载流程|动态挂载至写作中|可挂载节奏拆书卡|挂载 [^，。\n]*提高完读率|挂载 \$\{su\.title\}|mounted skill|mounted skills|no mounted skills|调整技能|该历史技能|技能放置失败|阶段技能与流程卡|该临时卡已失效|scene beats|chapter draft|audit critique|low fit score|new entities not synced|正在运行能力\.\.\.|应用预览|可直接用于写作的职责卡|Skill 卡组|skill 卡组|skill cards|职责单一|单职责|临时卡|本章技能卡|项目技能卡|技能需要|技能卡不允许|技能卡当前|章节临时卡|临时写法卡|临时规划卡|当前作品无权使用该临时卡|本地技能|已持久化技能|付费技能卡|技能卡版本|技能卡缺少|主笔技能|Writer overlay|技能插件|虚构的 skill|技能卡为模板化输出|技能卡必要字段|两个不同且存在的技能卡|已授权的技能卡融合|规则约束时挂载|自适应挂载/);
    expect(`${fusionTests}\n${dbSkillVersioningTests}`).not.toContain('叠加世界观型 Skill');
  });
});
